#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Canary-Stability
Version  : 2012
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Canary-Stability-2012.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Canary-Stability-2012.tar.gz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Canary-Stability-license
Requires: perl-Canary-Stability-man

%description
NAME
Canary::Stability - canary to check perl compatibility for schmorp's
modules

%package license
Summary: license components for the perl-Canary-Stability package.
Group: Default

%description license
license components for the perl-Canary-Stability package.


%package man
Summary: man components for the perl-Canary-Stability package.
Group: Default

%description man
man components for the perl-Canary-Stability package.


%prep
%setup -q -n Canary-Stability-2012

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Canary-Stability
cp COPYING %{buildroot}/usr/share/doc/perl-Canary-Stability/COPYING
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Canary/Stability.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Canary-Stability/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Canary::Stability.3
